use_frameworks!

platform :ios, '8.0'

target 'IDLToolBox_Example' do
  pod 'IDLToolBox', :path => '../'

  target 'IDLToolBox_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
